[package]
name = "cantrip-timer-component"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-timer-interface = { path = "../cantrip-timer-interface" }
cantrip-timer-service = { path = "../cantrip-timer-service" }
log = "0.4"

[lib]
name = "cantrip_timer_component"
path = "src/run.rs"
crate-type = ["staticlib"]
