[package]
name = "cantrip-security-component"
version = "0.1.0"
edition = "2018"

[dependencies]
cantrip-allocator = { path = "../../DebugConsole/cantrip-allocator" }
cantrip-logger = { path = "../../DebugConsole/cantrip-logger" }
cantrip-panic = { path = "../../DebugConsole/cantrip-panic" }
cantrip-security-common = { path = "../cantrip-security-common" }
cantrip-security-coordinator = { path = "../cantrip-security-coordinator" }
log = "0.4"

[lib]
name = "cantrip_security_coordinator"
path = "src/run.rs"
crate-type = ["staticlib"]
