[package]
name = "cantrip-security-component"
version = "0.1.0"
edition = "2018"

[dependencies]
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-security-interface = { path = "../cantrip-security-interface" }
cantrip-security-coordinator = { path = "../cantrip-security-coordinator" }
log = "0.4"

[lib]
name = "cantrip_security_coordinator"
path = "src/run.rs"
crate-type = ["staticlib"]
