[package]
name = "cantrip-security-coordinator"
version = "0.1.0"
edition = "2021"

[features]
default = ["fake"]  # TODO(sleffler): sel4 once it exists
fake = []
sel4 = []

[dependencies]
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-memory-interface = { path = "../../MemoryManager/cantrip-memory-interface" }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-security-interface = { path = "../cantrip-security-interface" }
cantrip-storage-interface = { path = "../../StorageManager/cantrip-storage-interface" }
log = "0.4"
postcard = { version = "0.7", features = ["alloc"], default-features = false }
