[package]
name = "cantrip-security-coordinator"
version = "0.1.0"
edition = "2018"

[features]
default = ["fake"]  # TODO(sleffler): sel4 once it exists
fake = []
sel4 = []

[dependencies]
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-security-common = { path = "../cantrip-security-common" }
cantrip-storage-interface = { path = "../../StorageManager/cantrip-storage-interface" }
log = "0.4"
postcard = "0.7"
