[package]
name = "cantrip-proc-manager"
version = "0.1.0"
description = "Cantrip OS ProcessManager services"
edition = "2018"

[dependencies]
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-proc-common = { path = "../cantrip-proc-common" }
log = "0.4"
smallstr = "0.2"
spin = "0.9"
