cargo-features = ["edition2021"]

[package]
name = "cantrip-proc-manager"
version = "0.1.0"
description = "Cantrip OS ProcessManager services"
edition = "2021"

[dependencies]
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-proc-interface = { path = "../cantrip-proc-interface" }
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
log = "0.4"
postcard = { version = "0.7", features = ["alloc"], default-features = false }
smallstr = "0.2"
spin = "0.9"
