cargo-features = ["edition2021"]

[package]
name = "cantrip-proc-manager"
version = "0.1.0"
description = "Cantrip OS ProcessManager services"
edition = "2021"
build = "build.rs"

[build-dependencies]
sel4-config = { path = "../../cantrip-os-common/src/sel4-config" }

[features]
default = []
CONFIG_CAPDL_LOADER_CC_REGISTERS = []
CONFIG_CAPDL_LOADER_WRITEABLE_PAGES = []
CONFIG_DEBUG_BUILD = []
CONFIG_KERNEL_MCS = []
CONFIG_SMP_SUPPORT = []

[dependencies]
cstr_core = "0.2.3"
hashbrown = { version = "0.11", features = ["ahash-compile-time-rng"] }
cantrip-io = { path = "../../DebugConsole/cantrip-io" }
cantrip-proc-interface = { path = "../cantrip-proc-interface" }
cantrip-memory-interface = { path = "../../MemoryManager/cantrip-memory-interface" }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
log = "0.4"
sel4-sys = { path = "../../cantrip-os-common/src/sel4-sys" }
smallstr = "0.2"
spin = "0.9"
static_assertions = "1.1"
