[package]
name = "cantrip-process-manager"
version = "0.1.0"
description = "Cantrip OS ProcessManager services"
edition = "2018"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
cantrip-allocator = { path = "../../DebugConsole/cantrip-allocator" }
cantrip-logger = { path = "../../DebugConsole/cantrip-logger" }
cantrip-proc-common = { path = "../cantrip-proc-common" }
log = "0.4"
panic-halt = "0.2.0"

[lib]
name = "cantrip_process_manager"
path = "src/run.rs"
crate-type = ["staticlib"]
