[package]
name = "cantrip-os-common"
version = "0.1.0"
edition = "2018"

[dependencies]
capdl = { path = "src/capdl" }
cantrip-os-model = { path = "src/cantrip-os-model" }
cantrip-slot-allocator = { path = "src/cantrip-slot-allocator" }
sel4-sys = { path = "src/sel4-sys" }
