cargo-features = ["edition2021"]

[package]
name = "cantrip-proc-component"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr_core = { version = "0.2.3", default-features = false }
cantrip-memory-interface = { path = "../../MemoryManager/cantrip-memory-interface" }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-proc-interface = { path = "../cantrip-proc-interface" }
cantrip-proc-manager = { path = "../cantrip-proc-manager" }
log = "0.4"
postcard = { version = "0.7", features = ["alloc"], default-features = false }

[lib]
name = "cantrip_process_manager"
path = "src/run.rs"
crate-type = ["staticlib"]
