[package]
name = "cantrip-proc-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
cstr_core = "0.2.3"
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
postcard = { version = "0.7", features = ["alloc"], default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
