[package]
name = "cantrip-proc-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr_core = "0.2.3"
cantrip-memory-interface = { path = "../../MemoryManager/cantrip-memory-interface" }
cantrip-io = { path = "../../DebugConsole/cantrip-io" }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
log = "0.4"
postcard = { version = "0.7", features = ["alloc"], default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
