[package]
name = "cantrip-shell"
version = "0.1.0"
authors = ["Matt Harvey <mattharvey@google.com>"]
edition = "2018"

[dependencies]
cantrip-io = { path = "../cantrip-io" }
cantrip-line-reader = { path = "../cantrip-line-reader" }
log = "0.4"
