[package]
name = "cantrip-proc-common"
version = "0.1.0"
edition = "2018"

[dependencies]
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
postcard = { version = "0.7", features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
