[package]
name = "cantrip-storage-manager"
version = "0.1.0"
edition = "2018"

[dependencies]
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
cantrip-storage-interface = { path = "../cantrip-storage-interface" }
log = "0.4"
