[package]
name = "cantrip-timer-service"
version = "0.1.0"
edition = "2021"

[dependencies]
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-timer-interface = { path = "../cantrip-timer-interface" }
log = "0.4"
opentitan-timer = { path = "../opentitan-timer" }
spin = "0.9"
