cargo-features = ["edition2021"]

[package]
name = "cantrip-storage-component"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr_core = { version = "0.2.3", default-features = false }
cantrip-os-common = { path = "../../cantrip-os-common" }
cantrip-storage-interface = { path = "../cantrip-storage-interface" }
cantrip-storage-manager = { path = "../cantrip-storage-manager" }
log = "0.4"
postcard = { version = "0.7", features = ["alloc"], default-features = false }

[lib]
name = "cantrip_storage_manager"
path = "src/run.rs"
crate-type = ["staticlib"]
