cargo-features = ["edition2021"]

[package]
name = "cantrip-vec-core"
version = "0.1.0"
edition = "2021"

[dependencies]
cantrip-ml-interface = { path = "../cantrip-ml-interface" }
modular-bitfield = "0.11.2"
log = "0.4"
xmas-elf = { git = "https://github.com/nrc/xmas-elf" }
