[package]
name = "cantrip-vec-core"
version = "0.1.0"
edition = "2021"

[dependencies]
cantrip-io = { path = "../../DebugConsole/cantrip-io" }
cantrip-ml-shared = { path = "../cantrip-ml-shared" }
modular-bitfield = "0.11.2"
log = "0.4"
