[package]
name = "cantrip-storage-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
cstr_core = "0.2"
cantrip-security-interface = { path = "../../SecurityCoordinator/cantrip-security-interface" }
postcard = "0.7"
